### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by liyufeng1983** [mediaelement/mediaelement-plugins#34]
mediaelement-and-player.js:8808 Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at http://ecfd13.pfizer.com/sites/KAMCoE/SiteContent/js/VideoJs/build/mediaelement-and-player.js:8808:11
    at Array.forEach (native)
    at http://ecfd13.pfizer.com/sites/KAMCoE/SiteContent/js/VideoJs/build/mediaelement-and-player.js:8807:6
    at Object.27.2 (http://ecfd13.pfizer.com/sites/KAMCoE/SiteContent/js/VideoJs/build/mediaelement-and-player.js:8820:3)
    at s (http://ecfd13.pfizer.com/sites/KAMCoE/SiteContent/js/VideoJs/build/mediaelement-and-player.js:11:257)
    at e (http://ecfd13.pfizer.com/sites/KAMCoE/SiteContent/js/VideoJs/build/mediaelement-and-player.js:11:428)
    at http://ecfd13.pfizer.com/sites/KAMCoE/SiteContent/js/VideoJs/build/mediaelement-and-player.js:11:446

**Comment by rafa8626** [comment]
If you can provide a URL so I can check this issue I'd appreciate it. Thanks

**Comment by rafa8626** [comment]
Closing this issue since no response has been posted on the past week. If you want this to be reopened, please let us know. Thanks

----------
Please star us at https://github.com/mediaelement/mediaelement and https://github.com/mediaelement/mediaelement-plugins to continue improving the package and giving it more popularity; also tell your friends/coworkers/etc. to support the project, if you don't mind.It would be greatly appreciated it
