### ISSUE TITLE
Qualities selector does not disappear

### ISSUE THREAD

**Issue by KhodyrevDS** [mediaelement/mediaelement-plugins#69]
inEvents has added to qualitiesButton, but outEvents  has added to qualities-selector.

When mouse over qualitiesButton Qualities selector will be shown and when mouse leave button and not leave Qualities selector, Qualities selector will not disappear.

**Comment by rafa8626** [comment]
http://dev-portal.videonotion.com/web/p/watch?v=63840f91-b9b7-49dc-b552-a784b0622d39 has this issue correct?

**Comment by KhodyrevDS** [comment]
It's old version MediaElement

**Comment by rafa8626** [comment]
Do you happen to know which version of the plugin you are using?

**Comment by KhodyrevDS** [comment]
I downloaded https://github.com/mediaelement/mediaelement-plugins/tree/master/dist/quality

**Comment by rafa8626** [comment]
I see. I'll check this in the course of the day. Thanks.

**Comment by rafa8626** [comment]
I have checked this, and it is expected behavior: if you leave the button but the cursor is still in the area where the options are displayed, they shouldn't go away. Once you select one, it will disappear. In your website you are using an old version of the `Source Chooser` package. I'll recommend you to upgrade to the latest version of both MediaElement and use the `Quality` plugin
