### ISSUE TITLE
Can't cast HLS audio only

### ISSUE THREAD

**Issue by sergioavazquez** [mediaelement/mediaelement-plugins#78]
I'm using the lastest versions of mediaelement and mediaelement-plugins and attempting to cast HLS radios to a chromecast device.

I had no problems casting HLS video, live and vod but whenever I cast a radio it doesn't work.

Reproduction stops on local machine, but it never seems to finish loading on the casting device. 
Chunks keep being loaded and there are no errors on the console. 

Any ideas on what might be going on? Can anyone reproduce this?

Thanks in advance.

**Comment by sergioavazquez** [comment]
Makes sense. It would be a great new feature though. I hope there's no need for it and you can find a way to make it work as it currently is! Good luck!!

**Comment by rafa8626** [comment]
OK I've checked this, and I added some more mime types to allow MP3 to be played; however, if I understood correctly, in order to play an audio HLS you need to give your receiver app that permission, and I don't think the default receiver allows you to do audio streaming. Check this page: https://developers.google.com/cast/docs/player, because that library also plays an important role for streaming. I don't think I can do anything else in terms of the sender, since it sends the right information. It's now more about the app you develop to receive that media type

**Comment by rafa8626** [comment]
Please star this repo so we can continue supporting it. Thanks

**Comment by sergioavazquez** [comment]
Thanks @rafa8626, I'm going to evaluate implementing it!
